<a href="https://colab.research.google.com/github/mars241/PYTHON/blob/main/A_A_M_WCS_Qu%C3%AAte_NumPy_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [ ]:

import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that
                  #Ici, nous renommons numpy en np(alias), c'est plus court, et tout le monde le fait.

# Mission 1 : Display the version of NumPy you are running
# Mission 1 : Afficher la version de NumPy que vous utilisez
np.version.version

'1.21.6'

In [ ]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])

# Mission 2 : Créer un tableau NumPy(matrix) d'une longueur de 3, qui contient ces 3 flottants : 0.8, 0.6, 0.4
# Résultat attendu : array([0.8, 0.6, 0.4])

table_numpy = np.array([0.8, 0.6, 0.4])
print(table_numpy)
#"data_table.shape"Voir le nombre de lignes et de colonnes de la table numpy
table_numpy.shape

# Résultat attendu :Matrixe à 3 colonnes & 1 ligne

[0.8 0.6 0.4]


(3,)

In [ ]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements,
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])


# Mission 3 : Créer une fonction qui utilise la fonction np.random.random() pour retourner un tableau avec 10 éléments aléatoires,
# qui doivent tous être supérieurs à 0.25 et inférieurs à 1.0

# Exemple de résultat attendu : array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])


# Methode0 : "np.random.random" (NB: Ne prends pas comme argument les Floats!)
# "np.random.random(t)" : est un tuple t qui construit un tableau de format t
#contenant des valeurs indépendamment et uniformément réparties sur [0, 1] :
# Synthaxe:"np.random.random(a,b)"; a=nbr ligne & b=nbre colonne .
tabl1_numpy=np.random.random((1,10))
tabl1_numpy

# Methode1: module/fct "enumerate"
#nombres = list(range(2, 9))
#for i, n in enumerate(nombres):
#  output[i] = 1 / n
#output

# Methode2 de "np.radom.uniform()""
#np.random.uniform (0.25, 1.0, 10)

array([[0.54293832, 0.74410039, 0.03725006, 0.85909988, 0.57707463,
        0.89202179, 0.7006648 , 0.99440359, 0.99765225, 0.04970285]])

In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here

# Mission 4 : Que fait la méthode np.empty() ? Ne vous contentez pas de copier la documentation, expliquez avec vos propres mots ici.

# Rmq: le "numpy" ne traite pas les Floats par nature! Passons par les listes:
nombres = list(range(2,1))
nombres
# Pour cela utilisons les "np.empty()" : qui est utilisé pour la création de routine
#numpy.empty(shape, dtype=float, order='C', *, like=None)

#Retourne un nouveau tableau de forme et de type donnés, sans initialiser les entrées.
#shape Forme du tableau vide, par exemple, (2, 3) ou 2.	Requis
#dtype Type de données de sortie souhaité pour le tableau, par exemple, numpy.int8.
#La valeur par défaut est numpy.float64. optional
output = np.empty(len(nombres))
output



array([], dtype=float64)

In [ ]:
# Mission 5 : Create an array filled with only zeros. You can choose the length of this array.

# Mission 5 : Créer un tableau rempli uniquement de zéros. Vous pouvez choisir la longueur de ce tableau.

# Methode1:"np.zeros"
#Retourne un nouveau tableau dont les valeurs sont égales à zéro.
matrice=np.zeros((5,), dtype=int)
matrice

#nbre de colonne d'une matrice "matrice.ndim"
#matrice.ndim

#nbre de ligne d'une matrice "matrice.size"
#matrice.size

array([0, 0, 0, 0, 0])

In [ ]:
# Mission 6 : Create an array filled with 10 random integers.
# Mission 6 : Créer un tableau rempli de 10 entiers aléatoires.
notes = np.random.randint(20, size=(3, 10)) # génère une matrice d'entiers entre 0 et (20-1), 3 lignes & 10 colonnes
notes

array([[ 4, 15, 17,  8,  6, 13,  2, 17,  4, 17],
       [17, 11, 13, 19,  8, 18,  6, 19,  9, 14],
       [12, 19, 17, 13, 16, 11, 13,  9, 17,  4]])

In [ ]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.
# Mission 7 : Créez un tableau qui contient 50 valeurs choisies au hasard uniquement parmi ces nombres : 0, 1, 2, 3, 4, 5, 6, 7.

nombres_tab = np.random.randint(8, size=(1, 50))
nombres_tab


array([[1, 3, 5, 0, 7, 6, 1, 5, 7, 1, 3, 1, 0, 1, 2, 5, 2, 5, 7, 0, 5, 2,
        4, 4, 0, 5, 6, 5, 3, 5, 7, 6, 6, 6, 7, 1, 6, 1, 5, 3, 6, 5, 5, 0,
        5, 3, 2, 3, 1, 1]])

In [ ]:
# Mission 8 : Use the slicing operator to return the items between position 3 and 6 inclusive, from the array in mission 6
# Mission 8 : Utiliser l'opérateur de découpage pour retourner les éléments entre les positions 3 et 6 inclus, du tableau de la mission 6.
notes1 = np.array([[ 4, 15, 17,  8,  6, 13,  2, 17,  4, 17],
       [17, 11, 13, 19,  8, 18,  6, 19,  9, 14],
       [12, 19, 17, 13, 16, 11, 13,  9, 17,  4]])
print(notes1)
#
print("Parmi toutes les rangées, les éléments de la 3ème; 4eme; 5eme & 6ème colonne sont succintement:", notes1[:,2], notes1[:,3], notes1[:,4], notes1[:,2])

# la matrice découpée de la 3eme à la 6eme
print("la matrice de ci_dessus découpée de la 3eme à la 6eme est:" , notes1[:, [2, 7],  ])

#print(notes1[:, -2:]) # Synthaxe pour les deux dernières colonnes
# Autrement,exiber chaque élement avec "array.item(Numéro_index)""
#notes1.item (2)


[[ 4 15 17  8  6 13  2 17  4 17]
 [17 11 13 19  8 18  6 19  9 14]
 [12 19 17 13 16 11 13  9 17  4]]
Parmi toutes les rangées, les éléments de la 3ème; 4eme; 5eme & 6ème colonne sont succintement: [17 13 17] [ 8 19 13] [ 6  8 16] [17 13 17]
la matrice de 'notes1' découpée de la 3eme à la 6eme est: [[17 17]
 [13 19]
 [17  9]]


In [ ]:
from numpy.core.fromnumeric import argmin
# Mission 9 : Use the `argmin()` method to return the index of the smallest element in the array from mission 6
# Mission 9 : Utilisez la méthode `argmin()` pour retourner l'index du plus petit élément du tableau de la mission 6.
notes1 = np.array([[ 4, 15, 17,  8,  6, 13,  2, 17,  4, 17],
       [17, 11, 13, 19,  8, 18,  6, 19,  9, 14],
       [12, 19, 17, 13, 16, 11, 13,  9, 17,  4]])
print(notes1)
print("le minimun de la matrice ci-dessus est:", argmin(notes1))


[[ 4 15 17  8  6 13  2 17  4 17]
 [17 11 13 19  8 18  6 19  9 14]
 [12 19 17 13 16 11 13  9 17  4]]
le minimun de la matrice ci-dessus est: 6


In [ ]:
# Mission 10 : Using the `where()` method, return the indices of all the values in the array from mission 6 that are greater than their median value.
# Mission 10 : En utilisant la méthode `where()`, retournez les indices de toutes les valeurs du tableau de la mission 6 qui sont plus grandes que leur valeur médiane.

notes1 = np.array([[ 4, 15, 17,  8,  6, 13,  2, 17,  4, 17],
       [17, 11, 13, 19,  8, 18,  6, 19,  9, 14],
       [12, 19, 17, 13, 16, 11, 13,  9, 17,  4]])
print(notes1)
arr1 = np.median(notes1) # Médiane générale
print("la Médiane de la matrice ci-dessus est:",arr1)
# Obtenir les indices des éléments d'un tableau selon la condiction where
arr=np.where(notes1 > arr1)
print("les indices des éléments plus grandes que Médiane sont:",arr)

[[ 4 15 17  8  6 13  2 17  4 17]
 [17 11 13 19  8 18  6 19  9 14]
 [12 19 17 13 16 11 13  9 17  4]]
la Médiane de la matrice ci-dessus est: 13.0
les indices des éléments plus grandes que Médiane sont: (array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2]), array([1, 2, 7, 9, 0, 3, 5, 7, 9, 1, 2, 4, 8]))


In [ ]:
# Mission 11: Create 3 arrays filled with 5 random integers each, and place them in another array.
# You have now an array with (3, 5) shape. You can use the `shape` attribute to check it.
# Display the elements, with each column appearing on a different line (so there will be 5 lines with 3 values each)

# Mission 11 : Créez 3 tableaux remplis de 5 entiers aléatoires chacun, et placez-les dans un autre tableau.
# Vous avez maintenant un tableau avec la forme (3, 5). Vous pouvez utiliser l'attribut `shape` pour le vérifier.
# Affichez les éléments, chaque colonne apparaissant sur une ligne différente (il y aura donc 5 lignes avec 3 valeurs chacune).

tb1= np.random.randint(10, size=(1, 5)) # tableaux d'entiers aléatoires entre 0 et 10 de dimension (1,5): 1 ligne & 5 colonnes/valeurs
tb2= np.random.randint(10, size=(1, 5))
tb3= np.random.randint(10, size=(1, 5))
print(tb1, tb2, tb3)
#  A travailler encore la synthaxe du "np.ndarray" !
#data = np.ndarray((tb1),(tb2),(tb3))
#print(type(data))
#print(data.shape)

#Autrement définir 3 tableaux suite d'entiers croissant de dim(1,5)
A,B,C = (np.full((1,5),k) for k in range(3))
D = np.block([[A],[B],[C]])
print("un autre tableau de tableaux est:", D)
print(type(D))
print(D.shape)

[[6 5 7 4 6]] [[5 7 5 4 0]] [[3 7 2 7 0]]
un autre tableau de tableaux est: [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
<class 'numpy.ndarray'>
(3, 5)


In [ ]:
# Mission 12: Create an array and fill it with 20 random float values.
# Create a function that returns the smallest and largest value it contains, with their indexes!
# You are allowed to use `min()` and `max()` methods.
# Example with a shorter array: [300, 500, 1000, 700, 100, 600] -> (4, 100), (2, 1000)
# Example with a shorter array: [80, 50, 90, -20, 100, 10] -> (3, -20), (4, 100)

# Mission 12 : Créez un tableau et remplissez-le avec 20 valeurs flottantes aléatoires.
# Créez une fonction qui retourne la plus petite et la plus grande valeur qu'il contient, avec leurs index !
# Vous pouvez utiliser les méthodes `min()` et `max()`.
# Exemple avec un tableau plus court : [300, 500, 1000, 700, 100, 600] -> (4, 100), (2, 1000)
# Exemple avec un tableau plus court : [80, 50, 90, -20, 100, 10] -> (3, -20), (4, 100)

tb=np.random.randint(1000, size=(1, 20))
mini=np.min(tb) # le minimum
maxi=np.max(tb) # le Maximum
ind_mi=np.where(tb == mini) #index du minimum
ind_ma=np.where(tb == maxi) #index du Maximum
print(mini, maxi, ind_mi, ind_ma )

# A creuser plus : utilisation d'une fonction!
#def min_max(mini,maxi):
#  mini=np.min(tb)
#  maxi=np.max(tb)
#  ind_2m=np.where((tb> mini) and (tb< maxi))
#  return(tb, mini, maxi,ind_2m)

tb


145 880 (array([0]), array([11])) (array([0]), array([6]))


array([[575, 365, 643, 389, 343, 839, 880, 329, 825, 723, 314, 145, 567,
        751, 175, 403, 345, 630, 833, 703]])

In [ ]:
# Mission 13: Create 2 arrays, randomly fill them with 20 int values between 0 and 10.
# Return all indices where the values of the 2 arrays happen to be equal.
# If no values are equal at the same indices across the 2 arrays, it will return an empty structure.
# Example with shorter arrays: np.array([1, 3, 5, 7]) & np.array([2, 3, 5, 8]) -> np.array([1, 2])
# Example with shorter arrays: np.array([1, 1, 1, 1]) & np.array([1, 2, 3, 4]) -> np.array([0])

# Mission 13 : Créer 2 tableaux, les remplir aléatoirement avec 20 valeurs int entre 0 et 10.
# Retourne tous les indices où les valeurs des 2 tableaux sont égales.
# Si aucune valeur n'est égale aux mêmes indices dans les 2 tableaux, il retournera une structure vide.
# Exemple avec des tableaux courts : np.array([1, 3, 5, 7]) & np.array([2, 3, 5, 8]) -> np.array([1, 2])
# Exemple avec des tableaux plus courts : np.array([1, 1, 1, 1]) & np.array([1, 2, 3, 4]) -> np.array([0])

tbx1=np.random.randint(10, size=(1, 20))
tbx2=np.random.randint(10, size=(1, 20))
print(tbx1, tbx2)
print((tbx1 == tbx2).any()) #Renvoie True si un des couples de valeurs est égal, sinon False

print(np.where(tbx1 == tbx2)) #"np.where(condiction)" :Renvoie les indices qui vérifient la condiction

[[5 4 6 3 4 2 9 6 1 1 2 1 4 8 2 6 7 5 7 2]] [[5 2 2 4 7 0 3 2 7 4 6 9 1 1 0 7 4 0 4 4]]
True
(array([0]), array([0]))


In [ ]:
# Mission 14: now, just compare both arrays of mission 13 with this command (change the name of arrays): array1 == array2

#Mission 14 : maintenant, il suffit de comparer les deux tableaux de la mission 13 avec cette commande (changer le nom des tableaux) : tableau1 == tableau2


tbx1=np.random.randint(10, size=(1, 20))
tbx2=np.random.randint(10, size=(1, 20))
np.where(tbx1 == tbx1)
#tbx2.rename(np.where(tbx1 == tbx1)) # A revoir la synthaxe de replace()!
print(tbx2)