<a href="https://colab.research.google.com/github/mars241/PYTHON/blob/main/AFaire_02_Broadcasting_avec_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Voici la définition du broadcasting qu'on peut trouver sur le site de Numpy

> Le terme `broadcasting` décrit comment numpy traite les tableaux de différentes formes lors des opérations arithmétiques. Sous réserve de certaines contraintes, le plus petit tableau est «diffusé» à travers le plus grand tableau afin qu'ils aient des formes compatibles. La diffusion fournit un moyen de vectoriser les opérations de tableau afin que la boucle se produise en C au lieu de Python. Il le fait sans faire de copies inutiles des données et conduit généralement à des implémentations d'algorithmes efficaces. Il existe cependant des cas où le broadcasting est une mauvaise idée car elle conduit à une utilisation inefficace de la mémoire qui ralentit le calcul.

Considérons l'opération suivante:

In [ ]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b # on peut aisément deviner la reponse

array([5, 6, 7])

Mais qu'en est-il de ceci :

In [ ]:
matrice = np.random.randint(20, size=(3, 3))
matrice

array([[16,  2,  0],
       [ 1, 12,  0],
       [16,  9,  2]])

In [ ]:
a

array([0, 1, 2])

In [ ]:
matrice + a # ici les 2 tableaux n'ont pas la même taille

array([[16,  3,  2],
       [ 1, 13,  2],
       [16, 10,  4]])

Ici s'est produit, le phénomène de broadcasting, la forme du plus petit tableau a été adapté pour avoir la même que la grande. C'est équivalent à ceci :

In [ ]:
np.vstack([a, a, a])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
matrice + np.vstack([a, a, a])

array([[16,  3,  2],
       [ 1, 13,  2],
       [16, 10,  4]])

Il existe 3 règles à connaitre pour le broadcasting

> Règle 1 : si 2 tableaux ont des ndim différents, le shape de celui avec le ndim inférieur est augmenté par des 1 à gauches pour avoir le même ndim que l'autre

In [ ]:
m = np.random.randint(10, size=(2, 3))
m

array([[5, 0, 5],
       [9, 8, 0]])

In [ ]:
a

array([0, 1, 2])

In [ ]:
m # (2, 3) --> (2, 3)
a # (3)    ---> (1, 3)

array([0, 1, 2])

> Règle 2 : Si le shape de 2 tableaux n'est pas égale dans une dimension quelconque, celui qui a un 1 à cette dimension est étendu pour atteindre le nombre d'éléments que l'autre a à cette dimension

In [ ]:
m # (2, 3) --> (2, 3)  ---> (2, 3)
a # (3)    ---> (1, 3)  ---->(2, 3) #grace à vstack

In [ ]:
np.vstack([a, a])

array([[0, 1, 2],
       [0, 1, 2]])

In [ ]:
m + a

array([[5, 1, 7],
       [9, 9, 2]])

Un autre exemple

In [ ]:
m = np.arange(3).reshape((3, 1))
m

array([[0],
       [1],
       [2]])

In [ ]:
h = np.random.randint(3, size=(3,))
h

array([1, 2, 1])

In [ ]:
m.shape = (3, 1)
h.shape = (3, )

In [ ]:
# Regle 1
m.shape = (3, 1)
h.shape = (1, 3)

In [ ]:
h.reshape((1, 3))

array([[1, 2, 1]])

In [ ]:
np.vstack([h.reshape((1, 3))]* 3)

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [ ]:
# Regle 2
m.shape = (3, 1)
h.shape = (3, 3)

In [ ]:
m

array([[0],
       [1],
       [2]])

In [ ]:
np.hstack([m, m, m])

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
# Regle 2
m.shape = (3, 3)
h.shape = (3, 3)

In [ ]:
np.vstack([h.reshape((1, 3)),  h.reshape((1, 3)),  h.reshape((1, 3))])

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [ ]:
m + h

array([[1, 2, 1],
       [2, 3, 2],
       [3, 4, 3]])

Encore un exemple :

In [ ]:
m = np.ones((3, 2))
m

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
j = np.arange(3)
j

array([0, 1, 2])

In [ ]:
m.shape = (3, 2)
j.shape = (3)

In [ ]:
Règle 1
m.shape = (3, 2)
j.shape = (1, 3) # j.reshape((1, 3))

In [ ]:
np.vstack([j.reshape((1, 3)),  j.reshape((1, 3)),  j.reshape((1, 3))])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
Règle 2
m.shape = (3, 2)
j.shape = (3, 3)

In [ ]:
m + j

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [ ]:
m

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
j

array([0, 1, 2])

> Règle 3 : Si après Règle 1 et 2, les shapes, ne sont pas les mêmes, alors calcul impossible

# Utilité de brodcast

In [ ]:
x = np.random.randint(255, size=(6, 3))
x

array([[233, 160,  20],
       [ 88,  51,  86],
       [160, 253, 188],
       [205, 253,  65],
       [234, 111, 250],
       [155, 186, 172]])

In [ ]:
xmean = x.mean(axis=0)
xmean

array([179.16666667, 169.        , 130.16666667])

In [ ]:
x.shape

(6, 3)

In [ ]:
xmean.shape

(3,)

In [ ]:
xstd = x.std(axis=0)
xstd

array([51.37254996, 72.76675065, 79.36081457])

In [ ]:
x_centre_et_reduit = (x - xmean) / xstd
x_centre_et_reduit

array([[ 1.04790074, -0.12368286, -1.3881746 ],
       [-1.77461829, -1.62161975, -0.55652991],
       [-0.3730916 ,  1.15437338,  0.72873916],
       [ 0.50286259,  1.15437338, -0.82114413],
       [ 1.06736639, -0.79706733,  1.50998114],
       [-0.47041984,  0.23362318,  0.52712833]])

# Plus : Fancy Indexing

In [ ]:
x = np.random.randint(100, size=(5))
x

array([79, 22, 48,  3, 95])

In [ ]:
x[:2], x[2:4]

(array([79, 22]), array([48,  3]))

In [ ]:
x[1:4:2]

array([22,  3])

In [ ]:
x[[0,1,-1] ] # ceci est le fancy indexing. On indexe avec une liste des index de chaque élément

array([79, 22, 95])

In [ ]:
data = np.random.randint(100, size=(6, 3))
data

array([[11, 88, 17],
       [38, 37, 71],
       [53, 23, 66],
       [18,  4, 62],
       [89, 89,  3],
       [92, 97, 88]])

In [ ]:
data[:, [0, 2],  ]

array([[11, 17],
       [38, 71],
       [53, 66],
       [18, 62],
       [89,  3],
       [92, 88]])

In [ ]:
data[:, [2,0]]

array([[17, 11],
       [71, 38],
       [66, 53],
       [62, 18],
       [ 3, 89],
       [88, 92]])

In [ ]:
data[[2,1, 4] , :]

array([[53, 23, 66],
       [38, 37, 71],
       [89, 89,  3]])